"""
ml/train.py
────────────
Trainer classes for TCN, BiLSTM, and ST-GCN, plus the top-level
run_train() function that orchestrates the full training pipeline.

Usage (from terminal):
    python -m ml.train

What run_train() does:
  1. Loads .npy sequences from DATA_DIR (generated by dataset.py)
  2. Splits 70 % train / 10 % val / 20 % test
  3. Augments training data
  4. Converts to per-model tensor shapes
  5. Trains TCN → BiLSTM → ST-GCN with early stopping
  6. Saves best weights to ml/saved_models/
  7. Calibrates ensemble weights on validation set
  8. Prints full classification report
"""
import os
import json
from collections import Counter

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

from app.ml.config import (
    WEIGHTS_DIR, EPOCHS, BATCH_SIZE, LEARNING_RATE,
    AUGMENT, AUG_MULTIPLIER, DEVICE,
)
from app.ml.models.tcn_model    import TCNModel
from app.ml.models.bilstm_model import BiLSTMModel
from app.ml.models.stgcn_model  import STGCNModel, build_adjacency_matrix
from app.ml.preprocessing       import augment_dataset, preprocess_for_models
from app.ml.dataset             import load_dataset, load_gestures_from_summary


# ── Base trainer ──────────────────────────────────────────────────────────────

class _BaseTrainer:
    """Shared training loop used by all three trainers."""

    EARLY_STOP = 20   # stop if val accuracy doesn't improve for this many epochs

    def __init__(self, model: nn.Module, weight_filename: str):
        self.device     = DEVICE
        self.model      = model.to(self.device)
        self.weight_path = os.path.join(WEIGHTS_DIR, weight_filename)

    def _make_loaders(self, X_train, y_train, X_val, y_val):
        train_dl = DataLoader(
            TensorDataset(torch.FloatTensor(X_train), torch.LongTensor(y_train)),
            batch_size=BATCH_SIZE, shuffle=True,
        )
        val_dl = DataLoader(
            TensorDataset(torch.FloatTensor(X_val), torch.LongTensor(y_val)),
            batch_size=BATCH_SIZE,
        )
        return train_dl, val_dl

    def _run_epoch(self, loader, optimizer, criterion, train: bool):
        self.model.train(train)
        total_loss = correct = total = 0
        with torch.set_grad_enabled(train):
            for xb, yb in loader:
                xb, yb = xb.to(self.device), yb.to(self.device)
                if train:
                    optimizer.zero_grad()
                out  = self.model(xb)
                loss = criterion(out, yb)
                if train:
                    loss.backward()
                    nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
                    optimizer.step()
                total_loss += loss.item()
                correct    += (out.argmax(1) == yb).sum().item()
                total      += yb.size(0)
        return total_loss / len(loader), correct / total

    def train(self, X_train, y_train, X_val, y_val,
              epochs=EPOCHS, lr=LEARNING_RATE,
              class_weights=None, label=None):
        label = label or self.__class__.__name__
        print(f"\n  {label} running on: {self.device}")

        weight_tensor = class_weights.to(self.device) if class_weights is not None else None
        criterion = nn.CrossEntropyLoss(weight=weight_tensor, label_smoothing=0.1)
        optimizer = torch.optim.AdamW(self.model.parameters(), lr=lr, weight_decay=1e-3)
        scheduler = torch.optim.lr_scheduler.OneCycleLR(
            optimizer, max_lr=lr * 10, epochs=epochs,
            steps_per_epoch=max(1, len(X_train) // BATCH_SIZE),
        )

        train_dl, val_dl = self._make_loaders(X_train, y_train, X_val, y_val)
        best_acc     = 0.0
        patience_ctr = 0
        history      = {"epoch": [], "train_loss": [], "train_acc": [], "val_acc": []}

        for epoch in range(1, epochs + 1):
            train_loss, train_acc = self._run_epoch(train_dl, optimizer, criterion, train=True)
            scheduler.step()
            _, val_acc = self._run_epoch(val_dl, optimizer, criterion, train=False)

            history["epoch"].append(epoch)
            history["train_loss"].append(round(train_loss, 4))
            history["train_acc"].append(round(train_acc,  4))
            history["val_acc"].append(round(val_acc,   4))

            if val_acc > best_acc:
                best_acc     = val_acc
                patience_ctr = 0
                torch.save(self.model.state_dict(), self.weight_path)
            else:
                patience_ctr += 1

            if epoch % 10 == 0 or epoch == 1:
                print(f"  [{label}] Epoch {epoch:03d} | Loss: {train_loss:.4f} | "
                      f"Train: {train_acc:.4f} | Val: {val_acc:.4f}"
                      + ("  ← best" if patience_ctr == 0 else ""))

            if patience_ctr >= self.EARLY_STOP:
                print(f"  Early stopping at epoch {epoch}.")
                break

        print(f"  Best val accuracy: {best_acc:.4f}")
        # Save history
        with open(self.weight_path.replace(".pth", "_history.json"), "w") as f:
            json.dump(history, f, indent=2)

    def load_best(self):
        """Load the best saved weights back into the model."""
        self.model.load_state_dict(
            torch.load(self.weight_path, map_location=self.device)
        )
        self.model.eval()

    @torch.no_grad()
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Return softmax probabilities for a batch of inputs."""
        self.model.eval()
        x = torch.FloatTensor(X).to(self.device)
        return torch.softmax(self.model(x), dim=1).cpu().numpy()


# ── Concrete trainers ─────────────────────────────────────────────────────────

class TCNTrainer(_BaseTrainer):
    def __init__(self, model: TCNModel):
        super().__init__(model, "tcn_best.pth")

    def train(self, X_train, y_train, X_val, y_val, **kwargs):
        super().train(X_train, y_train, X_val, y_val, label="TCN", **kwargs)


class BiLSTMTrainer(_BaseTrainer):
    def __init__(self, model: BiLSTMModel):
        super().__init__(model, "bilstm_best.pth")

    def train(self, X_train, y_train, X_val, y_val, **kwargs):
        super().train(X_train, y_train, X_val, y_val, label="BiLSTM", **kwargs)


class STGCNTrainer(_BaseTrainer):
    def __init__(self, model: STGCNModel):
        super().__init__(model, "stgcn_best.pth")

    def train(self, X_train, y_train, X_val, y_val, **kwargs):
        super().train(X_train, y_train, X_val, y_val, label="ST-GCN", **kwargs)


# ── Full pipeline ──────────────────────────────────────────────────────────────

def run_train(gestures: list = None):
    """
    End-to-end training pipeline.

    1. Load dataset from DATA_DIR
    2. Split 70/10/20
    3. Augment training data
    4. Train TCN, BiLSTM, ST-GCN
    5. Calibrate ensemble weights
    6. Save ensemble metadata
    """
    gestures    = gestures or load_gestures_from_summary()
    num_classes = len(gestures)
    A           = build_adjacency_matrix()

    print("\n" + "=" * 55)
    print("  TRAINING PIPELINE")
    print("=" * 55)

    # ── Load ────────────────────────────────────────────────────
    print("\n[1/5] Loading dataset...")
    X, y = load_dataset(gestures=gestures)

    # 70 / 10 / 20 split
    X_tv, X_test, y_tv, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_tv, y_tv, test_size=0.125, random_state=42, stratify=y_tv
    )
    print(f"  Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

    # ── Augment ──────────────────────────────────────────────────
    if AUGMENT:
        print(f"\n[2/5] Augmenting training data (×{AUG_MULTIPLIER + 1})...")
        X_train, y_train = augment_dataset(X_train, y_train, multiplier=AUG_MULTIPLIER)

    # ── Preprocess ───────────────────────────────────────────────
    tr   = preprocess_for_models(X_train)
    val  = preprocess_for_models(X_val)
    test = preprocess_for_models(X_test)

    # Class weights for imbalanced sets
    counts        = Counter(y_train.tolist())
    total_samples = len(y_train)
    class_weights = torch.FloatTensor([
        total_samples / (num_classes * counts.get(i, 1))
        for i in range(num_classes)
    ])

    # ── Train TCN ────────────────────────────────────────────────
    print("\n[3/5] Training TCN...")
    tcn = TCNTrainer(TCNModel(63, num_classes))
    tcn.train(tr["tcn"], y_train, val["tcn"], y_val, class_weights=class_weights)
    tcn.load_best()

    # ── Train BiLSTM ─────────────────────────────────────────────
    print("\n[4/5] Training BiLSTM...")
    bilstm = BiLSTMTrainer(BiLSTMModel(63, 256, num_classes=num_classes))
    bilstm.train(tr["bilstm"], y_train, val["bilstm"], y_val, class_weights=class_weights)
    bilstm.load_best()

    # ── Train ST-GCN ─────────────────────────────────────────────
    print("\n[5/5] Training ST-GCN...")
    stgcn = STGCNTrainer(STGCNModel(3, num_classes, A))
    stgcn.train(tr["stgcn"], y_train, val["stgcn"], y_val, class_weights=class_weights)
    stgcn.load_best()

    # ── Calibrate ensemble weights on validation set ─────────────
    from app.ml.ensemble import EnsembleVoter
    ensemble = EnsembleVoter(tcn, bilstm, stgcn, gestures)
    ensemble.calibrate_weights(val, y_val)

    # Save ensemble metadata (gestures + calibrated weights)
    meta_path = os.path.join(WEIGHTS_DIR, "ensemble_weights.json")
    with open(meta_path, "w") as f:
        json.dump({
            "gestures": gestures,
            "weights":  ensemble.weights.tolist(),
        }, f, indent=2)

    # ── Final test report ─────────────────────────────────────────
    print("\n" + "=" * 55)
    print("  FINAL TEST ACCURACY")
    print("=" * 55)
    ensemble.evaluate(test, y_test, label="HELD-OUT TEST SET")

    print("\n✅ Training complete! Weights saved to:", WEIGHTS_DIR)


if __name__ == "__main__":
    run_train()